<!-- #include virtual="modules/global/displayListingCount.asp" -->
<h2>Search Thousands of Listings!</h2>
<!--<h2>Search Over <%'=vRoundedListingCount%> Listings</h2>-->
<p style="font-size:7pt;">* MLS rules require registration to view all listings.</p>


<table cellspacing="10" cellpadding="0" border="0">
<tr>
<td valign="top"><img src="/media/global/search/newregsavedsearches.gif" alt=""></td>
<td>
	<p>With our easy-to-use search system, the home of your dreams 
	is only a few clicks away! A number of different search types 
	are offered, allowing you to choose the search method that 
	best suits you.  
	</p>


	<!--<p>Use one of these map searches:</p>
	<ul style="list-style:inside disc;">
		<li>Map</li>
		<li>Map - City Limits</li>
		<li>Map - Zip Code</li>
		<li>Map - School District</li>
		<li>Map - Radius</li>
	</ul>-->
</td>
</tr>
<tr>
<td valign="top"><img src="/media/global/search/newreghome.gif" alt="" style="float:left;"></td>
<td><p>Use the Advanced Search Criteria to narrow your search to exactly what you want.</p></td>
</tr>
</table>


